# Numpy Demonstraion

# Array & rang

In [101]:
import numpy as np


In [102]:
array = np.arange(100)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
array.size*array.itemsize

400

In [104]:
a = np.array([[1,2], [2,3], [4,5]])
print(a.itemsize) # int occupy 4 Bits so
print(a.dtype)

4
int32


In [105]:
a

array([[1, 2],
       [2, 3],
       [4, 5]])

In [106]:
a = np.array([[1,2], [2,3], [4,5]], dtype = np.float64) 
print(a.itemsize) # float occupy 8 Bits so
print(a.dtype)
print(a.size)
print(a.shape) # row, column

8
float64
6
(3, 2)


In [107]:
a = np.array([[1,2], [2,3], [4,5]], dtype = complex) 
print(a)
print(a.itemsize) # float occupy 8 Bits so
print(a.dtype)
print(a.size)
print(a.shape) # row, column

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j]]
16
complex128
6
(3, 2)


In [108]:
a = np.array([1, 2, 3])
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.shape)

4
int32
3
(3,)


# Zeroes 


In [109]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [110]:
a = np.ones((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [111]:
l = np.arange(1, 5)
print(l)

[1 2 3 4]


In [112]:
l = np.arange(1, 5, 2) # ( start, stop, number of steps )
print(l)

[1 3]


In [113]:
l = np.linspace(1, 5, 10) # (start, stop, total number between start & stop with equal distance)
print(l)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# Reshape


In [114]:
a = np.array([[1,2], [2,3], [3,4]])
print(a)

[[1 2]
 [2 3]
 [3 4]]


In [115]:
a.reshape(2, 3) # 2*3 = 6 size of array

array([[1, 2, 2],
       [3, 3, 4]])

In [116]:
a.ravel() # flatern an array

array([1, 2, 2, 3, 3, 4])

In [117]:
print(a.min())
print(a.max())
print(a.sum())

1
4
15


In [118]:
print(a.sum(axis = 0))
print(a.sum(axis = 1))

[6 9]
[3 5 7]


In [119]:
print(np.sqrt(a))
print("Standard deviation : ",np.std(a))

[[1.         1.41421356]
 [1.41421356 1.73205081]
 [1.73205081 2.        ]]
Standard deviation :  0.9574271077563381


In [120]:
a = np.array([[1,2], [3,4]])
b = np.array([[6,7], [8,9]])
print(a+b)
print(a*b)
print(a/b)
print("Dot product : ",a.dot(b))

[[ 7  9]
 [11 13]]
[[ 6 14]
 [24 36]]
[[0.16666667 0.28571429]
 [0.375      0.44444444]]
Dot product :  [[22 25]
 [50 57]]


# Time comparison

In [121]:
import time

Size = 1000000

l1 = range(Size)
l2 = range(Size)
# print(l1)
n1 = np.array(Size)
n2 = np.array(Size)

start = time.time()
# print(start)
result = [((x + y) for x,y in zip(l1,l2))]
print(" , it took time : ", ( (time.time() - start)*10000 ), " sec")
# print( ((time.time() - start)*1000 ),"=======================================")

# print(n1)

start = time.time()
result = n1 + n2
print(" , it took time : ", ( (time.time() - start)*10000 ), " sec")


 , it took time :  0.0  sec
 , it took time :  0.0  sec


# Slicing & Stacking

In [127]:
a = np.array([6, 7, 8, 9, 10, 11])
print(a[1:4])
print(a[-3:-1])

[7 8 9]
[ 9 10]


In [129]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [132]:
print(a[1, 2])
print(a[0:2, 2])
print(a[0:2,0:2])

6
[3 6]
[[1 2]
 [4 5]]


In [134]:
print(a[:,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [138]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


for cell in a.flat:
    print(cell)

# stacking

In [150]:
arr1 = np.arange(6).reshape(3, 2)
arr2 = np.arange(6, 12).reshape(3, 2)
print(arr1)
print("=====")
print(arr2)

[[0 1]
 [2 3]
 [4 5]]
=====
[[ 6  7]
 [ 8  9]
 [10 11]]


In [153]:
print(np.vstack((arr1, arr2))) # vertical stacking
print(np.hstack((arr1, arr2))) # Horizontal stacking

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [160]:
qq = np.hsplit(arr1, 2)
print(qq[0])
print(qq[1])
print('=========')
qq = np.vsplit(arr1, 3)
print(qq[0])
print(qq[1])
print(qq[2])

[[0]
 [2]
 [4]]
[[1]
 [3]
 [5]]
[[0 1]]
[[2 3]]
[[4 5]]


# Boolean array

In [161]:
qq = a>4
print(qq)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [162]:
print(a[qq]) # extracting elements having greater than 4

array([5, 6, 7, 8, 9])

In [165]:
a[qq] = -1 # replacing elemnts with conditions
print(a)

[[ 1  2  3]
 [ 4 -1 -1]
 [-1 -1 -1]]


# iterate numpy array using nditer

In [166]:
arr1 = np.arange(5, 21).reshape(4, 4)
print(arr1)


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [168]:
for x in np.nditer(arr1, order='C'): # c-order c_index
    print(x)


5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [169]:
for x in np.nditer(arr1, order='F'): # fortern order
    print(x)

5
9
13
17
6
10
14
18
7
11
15
19
8
12
16
20


In [170]:
for x in np.nditer(arr1, order='F', flags=['external_loop']): # fortern order w/external_loop
    print(x)

[ 5  9 13 17]
[ 6 10 14 18]
[ 7 11 15 19]
[ 8 12 16 20]


In [171]:
for x in np.nditer(arr1, op_flags=['readwrite']): # editing or changing values in array
    x[...]=x*x
print(arr1)

[[ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]
 [289 324 361 400]]


In [186]:
arr2 = np.arange(3, 15, 3).reshape(4, 1)
print(arr2)

[[ 3]
 [ 6]
 [ 9]
 [12]]


In [187]:
for x, y in np.nditer([arr2, arr1]):
    print(x, y)

3 25
3 36
3 49
3 64
6 81
6 100
6 121
6 144
9 169
9 196
9 225
9 256
12 289
12 324
12 361
12 400
